
# SPDX-License-Identifier: Apache-2.0
version: '3.8'

volumes:
  postgres_data:

networks:
  explorer-network:
    driver: bridge

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fabricexplorer
      POSTGRES_USER: hppoc
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - explorer-network

  explorer:
    build: .
    container_name: hyperledger-explorer
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: fabricexplorer
      DATABASE_USERNAME: hppoc
      DATABASE_PASSWD: password
      EXPLORER_APP_ROOT: app
      LOG_LEVEL_APP: debug
      LOG_LEVEL_DB: debug
      LOG_LEVEL_CONSOLE: info
      LOG_CONSOLE_STDOUT: false
      DISCOVERY_AS_LOCALHOST: true
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/explorer/logs
      - ./app/platform/fabric/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./wallet:/opt/explorer/wallet
    networks:
      - explorer-network
    restart: unless-stopped
